// Code generated by mockery v2.46.2. DO NOT EDIT.

package mocks

import (
	domain "case-study/leo/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// BookUsecase is an autogenerated mock type for the BookUsecase type
type BookUsecase struct {
	mock.Mock
}

// GetBySubject provides a mock function with given fields: ctx, req
func (_m *BookUsecase) GetBySubject(ctx context.Context, req domain.BookGetBySubjectRequest) (domain.BookGetBySubjectResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetBySubject")
	}

	var r0 domain.BookGetBySubjectResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.BookGetBySubjectRequest) (domain.BookGetBySubjectResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.BookGetBySubjectRequest) domain.BookGetBySubjectResponse); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(domain.BookGetBySubjectResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.BookGetBySubjectRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewBookUsecase creates a new instance of BookUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBookUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *BookUsecase {
	mock := &BookUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
